pipeline {
    agent any
    
    environment {
        PYTHON = 'python3'
        VENV_PATH = 'venv'
    }
    
    stages {
        stage('Setup') {
            steps {
                sh '${PYTHON} -m venv ${VENV_PATH}'
                sh '. ${VENV_PATH}/bin/activate && pip install -r requirements.txt'
            }
        }
        
        stage('Test') {
            steps {
                sh '. ${VENV_PATH}/bin/activate && python manage.py test'
            }
        }
        
        stage('Selenium Tests') {
            steps {
                script {
                    try {
                        // Start Django server in background
                        sh '. ${VENV_PATH}/bin/activate && python manage.py migrate'
                        sh '. ${VENV_PATH}/bin/activate && python manage.py runserver &'
                        
                        // Give server time to start
                        sleep 10
                        
                        // Run Selenium tests
                        sh '. ${VENV_PATH}/bin/activate && python manage.py test tests.test_selenium'
                    } finally {
                        // Stop Django server
                        sh 'pkill -f "python manage.py runserver" || true'
                    }
                }
            }
        }
        
        stage('Deploy') {
            when {
                branch 'main'
            }
            steps {
                sh '. ${VENV_PATH}/bin/activate && python manage.py collectstatic --noinput'
                // Add your deployment steps here
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}